#!/bin/sh

# PROVIDE: tredly-cc
# BEFORE:  LOGIN FILESYSTEMS
# KEYWORD: shutdown

. /etc/rc.subr

name="tredlycc"
rcvar="tredlycc_enable"

PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin"

command="/usr/local/bin/npm"

tredlycc_directory="/usr/local/nodejs/www"

start_cmd="${name}_start"
stop_cmd="${name}_stop"
restart_cmd="${name}_restart"
status_cmd="${name}_status"
log_cmd="${name}_log"
extra_commands="status log"

load_rc_config $name
: ${tredlycc}_enable:=no}

tredlycc_start()
{
    cd ${tredlycc_directory}
    env NODE_ENV=production ${command} start
}

tredlycc_stop()
{
    cd ${tredlycc_directory}
    ${command} stop
}

tredlycc_restart()
{
    cd ${tredlycc_directory}
    ${command} restart
}

tredlycc_status()
{
    cd ${tredlycc_directory}
    ${command} run list
}
tredlycc_log()
{
    cd ${tredlycc_directory}
    ${command} run logs
}

load_rc_config $name
run_rc_command "$1"
